# Generated by Django 6.1.1 on 2026-09-21 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('Recibida', 'Recibida'), ('Clasificada', 'Clasificada'), ('En proceso', 'En proceso'), ('Control de calidad', 'Control de calidad'), ('Lista para entrega', 'Lista para entrega'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada'), ('En espera', 'En espera')], default='Recibida', max_length=30)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagada', 'Pagada')], default='Pendiente', max_length=20)),
                ('fecha_estimada_entrega', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255)),
                ('numero_reprocesos', models.PositiveIntegerField(default=0)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('estado_inicial', models.CharField(blank=True, max_length=255)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='ordenes.orden')),
                ('tipo_prenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='catalogo.tipoprenda')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='catalogo.tarifa')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='ordenes.prenda')),
            ],
            options={
                'verbose_name': 'servicio de la prenda',
                'verbose_name_plural': 'servicios de la prenda',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('valor_total__gte', 0)), name='orden_valor_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='prenda',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='prenda_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ordenservicio',
            constraint=models.UniqueConstraint(fields=('prenda', 'tarifa'), name='orden_servicio_unico_por_prenda'),
        ),
        migrations.AddConstraint(
            model_name='ordenservicio',
            constraint=models.CheckConstraint(condition=models.Q(('valor_aplicado__gte', 0)), name='orden_servicio_valor_no_negativo'),
        ),
    ]
