# Generated by Django 6.1.1 on 2026-09-21 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_proceso', 'En proceso'), ('lista', 'Lista para entrega'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='recibida', max_length=12)),
                ('recibida_en', models.DateTimeField(auto_now_add=True)),
                ('entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('entregada_en', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='clientes.cliente')),
                ('operario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
                'ordering': ('-recibida_en',),
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=160)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='ordenes.orden')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prendas', to='catalogo.servicio')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='orden',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='orden_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='prenda',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='prenda_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='prenda',
            constraint=models.CheckConstraint(condition=models.Q(('valor_unitario__gte', 0)), name='prenda_valor_no_negativo'),
        ),
    ]
