# Generated by Django 6.1.1 on 2026-09-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('PA', 'Pasaporte'), ('NIT', 'NIT')], default='CC', max_length=3)),
                ('documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(blank=True, max_length=80)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('apellidos', 'nombres'),
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'documento'), name='cliente_documento_unico')],
            },
        ),
    ]
